#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Sep 20, 2020 03:08:14 PM IST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Register_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    Register_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    Register_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font11 = "-family {MS Sans Serif} -size 14 -weight bold"
        font12 = "-family {Courier New} -size 10"
        font13 = "-family {Segoe UI} -size 12"

        top.geometry("651x474")
        top.minsize(240, 1)
        top.maxsize(1924, 1061)
        top.resizable(0, 0)
        top.title("Register")
        top.configure(borderwidth="25")
        top.configure(background="#f2f2f2")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.031, rely=0.042, relheight=0.922
                , relwidth=0.925)
        self.Frame1.configure(relief='ridge')
        self.Frame1.configure(borderwidth="5")
        self.Frame1.configure(relief="ridge")
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(highlightbackground="#b1b1b1")
        self.Frame1.configure(highlightcolor="#646464646464")
        self.Frame1.configure(padx="25")

        self.name = tk.Entry(self.Frame1)
        self.name.place(relx=0.05, rely=0.128,height=20, relwidth=0.638)
        self.name.configure(background="white")
        self.name.configure(borderwidth="2")
        self.name.configure(disabledforeground="#a3a3a3")
        self.name.configure(font="TkFixedFont")
        self.name.configure(foreground="#000000")
        self.name.configure(insertbackground="black")

        self.D_id = tk.Entry(self.Frame1)
        self.D_id.place(relx=0.05, rely=0.24,height=20, relwidth=0.638)
        self.D_id.configure(background="white")
        self.D_id.configure(borderwidth="2")
        self.D_id.configure(disabledforeground="#a3a3a3")
        self.D_id.configure(font=font12)
        self.D_id.configure(foreground="#000000")
        self.D_id.configure(highlightbackground="#d9d9d9")
        self.D_id.configure(highlightcolor="black")
        self.D_id.configure(insertbackground="black")
        self.D_id.configure(selectbackground="blue")
        self.D_id.configure(selectforeground="white")

        self.Phno = tk.Entry(self.Frame1)
        self.Phno.place(relx=0.055, rely=0.352,height=20, relwidth=0.638)
        self.Phno.configure(background="white")
        self.Phno.configure(borderwidth="2")
        self.Phno.configure(disabledforeground="#a3a3a3")
        self.Phno.configure(font="TkFixedFont")
        self.Phno.configure(foreground="#000000")
        self.Phno.configure(highlightbackground="#d9d9d9")
        self.Phno.configure(highlightcolor="black")
        self.Phno.configure(insertbackground="black")
        self.Phno.configure(selectbackground="blue")
        self.Phno.configure(selectforeground="white")

        self.Age = tk.Entry(self.Frame1)
        self.Age.place(relx=0.055, rely=0.46,height=20, relwidth=0.638)
        self.Age.configure(background="white")
        self.Age.configure(borderwidth="2")
        self.Age.configure(disabledforeground="#a3a3a3")
        self.Age.configure(font="TkFixedFont")
        self.Age.configure(foreground="#000000")
        self.Age.configure(highlightbackground="#d9d9d9")
        self.Age.configure(highlightcolor="black")
        self.Age.configure(insertbackground="black")
        self.Age.configure(selectbackground="blue")
        self.Age.configure(selectforeground="white")

        self.Password = tk.Entry(self.Frame1)
        self.Password.place(relx=0.055, rely=0.579,height=20, relwidth=0.638)
        self.Password.configure(background="white")
        self.Password.configure(borderwidth="2")
        self.Password.configure(disabledforeground="#a3a3a3")
        self.Password.configure(font="TkFixedFont")
        self.Password.configure(foreground="#000000")
        self.Password.configure(highlightbackground="#d9d9d9")
        self.Password.configure(highlightcolor="black")
        self.Password.configure(insertbackground="black")
        self.Password.configure(selectbackground="blue")
        self.Password.configure(selectforeground="white")
        self.Password.configure(show="*")

        self.c_password = tk.Entry(self.Frame1)
        self.c_password.place(relx=0.055, rely=0.691,height=20, relwidth=0.638)
        self.c_password.configure(background="white")
        self.c_password.configure(borderwidth="2")
        self.c_password.configure(disabledforeground="#a3a3a3")
        self.c_password.configure(font="TkFixedFont")
        self.c_password.configure(foreground="#000000")
        self.c_password.configure(highlightbackground="#d9d9d9")
        self.c_password.configure(highlightcolor="black")
        self.c_password.configure(insertbackground="black")
        self.c_password.configure(selectbackground="blue")
        self.c_password.configure(selectforeground="white")
        self.c_password.configure(show="*")

        self.Name = tk.Label(self.Frame1)
        self.Name.place(relx=0.05, rely=0.069, height=21, width=96)
        self.Name.configure(anchor='w')
        self.Name.configure(background="#d9d9d9")
        self.Name.configure(disabledforeground="#a3a3a3")
        self.Name.configure(font=font13)
        self.Name.configure(foreground="#000000")
        self.Name.configure(justify='right')
        self.Name.configure(text='''Name''')

        self.Button1 = tk.Button(self.Frame1)
        self.Button1.place(relx=0.09, rely=0.801, height=44, width=207)
        self.Button1.configure(activebackground="#0000a0")
        self.Button1.configure(activeforeground="white")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#486cea")
        self.Button1.configure(borderwidth="5")
        self.Button1.configure(command=Register_support.reg)
        self.Button1.configure(compound='center')
        self.Button1.configure(cursor="hand2")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font11)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(justify='left')
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Register''')

        self.Docter_id = tk.Label(self.Frame1)
        self.Docter_id.place(relx=0.05, rely=0.183, height=21, width=96)
        self.Docter_id.configure(activebackground="#f9f9f9")
        self.Docter_id.configure(activeforeground="black")
        self.Docter_id.configure(anchor='w')
        self.Docter_id.configure(background="#d9d9d9")
        self.Docter_id.configure(disabledforeground="#a3a3a3")
        self.Docter_id.configure(font="-family {Segoe UI} -size 12 -weight normal -slant roman -underline 0 -overstrike 0")
        self.Docter_id.configure(foreground="#000000")
        self.Docter_id.configure(highlightbackground="#d9d9d9")
        self.Docter_id.configure(highlightcolor="black")
        self.Docter_id.configure(justify='right')
        self.Docter_id.configure(pady="5")
        self.Docter_id.configure(text='''Docter id''')

        self.Name_13 = tk.Label(self.Frame1)
        self.Name_13.place(relx=0.05, rely=0.297, height=21, width=126)
        self.Name_13.configure(activebackground="#f9f9f9")
        self.Name_13.configure(activeforeground="black")
        self.Name_13.configure(anchor='w')
        self.Name_13.configure(background="#d9d9d9")
        self.Name_13.configure(disabledforeground="#a3a3a3")
        self.Name_13.configure(font="-family {Segoe UI} -size 12 -weight normal -slant roman -underline 0 -overstrike 0")
        self.Name_13.configure(foreground="#000000")
        self.Name_13.configure(highlightbackground="#d9d9d9")
        self.Name_13.configure(highlightcolor="black")
        self.Name_13.configure(justify='right')
        self.Name_13.configure(pady="5")
        self.Name_13.configure(text='''Mobile Number''')

        self.Name_14 = tk.Label(self.Frame1)
        self.Name_14.place(relx=0.05, rely=0.412, height=21, width=96)
        self.Name_14.configure(activebackground="#f9f9f9")
        self.Name_14.configure(activeforeground="black")
        self.Name_14.configure(anchor='w')
        self.Name_14.configure(background="#d9d9d9")
        self.Name_14.configure(disabledforeground="#a3a3a3")
        self.Name_14.configure(font="-family {Segoe UI} -size 12 -weight normal -slant roman -underline 0 -overstrike 0")
        self.Name_14.configure(foreground="#000000")
        self.Name_14.configure(highlightbackground="#d9d9d9")
        self.Name_14.configure(highlightcolor="black")
        self.Name_14.configure(justify='right')
        self.Name_14.configure(pady="5")
        self.Name_14.configure(text='''Age''')

        self.Name_15 = tk.Label(self.Frame1)
        self.Name_15.place(relx=0.05, rely=0.526, height=21, width=96)
        self.Name_15.configure(activebackground="#f9f9f9")
        self.Name_15.configure(activeforeground="black")
        self.Name_15.configure(anchor='w')
        self.Name_15.configure(background="#d9d9d9")
        self.Name_15.configure(disabledforeground="#a3a3a3")
        self.Name_15.configure(font="-family {Segoe UI} -size 12 -weight normal -slant roman -underline 0 -overstrike 0")
        self.Name_15.configure(foreground="#000000")
        self.Name_15.configure(highlightbackground="#d9d9d9")
        self.Name_15.configure(highlightcolor="black")
        self.Name_15.configure(justify='right')
        self.Name_15.configure(pady="5")
        self.Name_15.configure(text='''Password''')

        self.Name_16 = tk.Label(self.Frame1)
        self.Name_16.place(relx=0.05, rely=0.641, height=21, width=151)
        self.Name_16.configure(activebackground="#f9f9f9")
        self.Name_16.configure(activeforeground="black")
        self.Name_16.configure(anchor='w')
        self.Name_16.configure(background="#d9d9d9")
        self.Name_16.configure(disabledforeground="#a3a3a3")
        self.Name_16.configure(font="-family {Segoe UI} -size 12 -weight normal -slant roman -underline 0 -overstrike 0")
        self.Name_16.configure(foreground="#000000")
        self.Name_16.configure(highlightbackground="#d9d9d9")
        self.Name_16.configure(highlightcolor="black")
        self.Name_16.configure(justify='right')
        self.Name_16.configure(pady="5")
        self.Name_16.configure(text='''Confirm Password''')

        self.Button1_18 = tk.Button(self.Frame1)
        self.Button1_18.place(relx=0.532, rely=0.801, height=44, width=207)
        self.Button1_18.configure(activebackground="#b30000")
        self.Button1_18.configure(activeforeground="white")
        self.Button1_18.configure(activeforeground="#fcfff4")
        self.Button1_18.configure(background="#ff3333")
        self.Button1_18.configure(borderwidth="5")
        self.Button1_18.configure(command=Register_support.Clear)
        self.Button1_18.configure(compound='center')
        self.Button1_18.configure(cursor="hand2")
        self.Button1_18.configure(disabledforeground="#a3a3a3")
        self.Button1_18.configure(font="-family {MS Sans Serif} -size 14 -weight bold -slant roman -underline 0 -overstrike 0")
        self.Button1_18.configure(foreground="#000000")
        self.Button1_18.configure(highlightbackground="#d9d9d9")
        self.Button1_18.configure(highlightcolor="black")
        self.Button1_18.configure(justify='right')
        self.Button1_18.configure(padx="5")
        self.Button1_18.configure(pady="0")
        self.Button1_18.configure(takefocus="0")
        self.Button1_18.configure(text='''Reset''')


if __name__ == '__main__':
    vp_start_gui()
