#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Nov 23, 2020 10:40:08 PM IST  platform: Windows NT

import sys

"""try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

#import final_screen_support"""
import os.path
from tkinter import *
from tkinter import ttk

def vp_start_gui():
    


"""def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    
    global w, w_win, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    #rt = root
    root = rt
    w = Toplevel (root)
    top = Toplevel1 (w)
    #final_screen_support.init(w, top, *args, **kwargs)
    return (w, top)"""

"""def destroy_Toplevel1():
    global w
    w.destroy()
    w = None"""


        

def final_screen_play():
    if __name__ == '__main__':
        vp_start_gui()

final_screen_play()





